export const basic = {
  "undefined": "Wastes",
  "B": "Snow-Covered Swamp",
  "G": "Snow-Covered Forest",
  "R": "Snow-Covered Mountain",
  "U": "Snow-Covered Island",
  "W": "Snow-Covered Plains",
}

export const fetchLand = {
  "UW": "Flooded Strand",
  "BU": "Polluted Delta",
  "BR": "Bloodstained Mire",
  "GR": "Wooded Foothills",
  "GW": "Windswept Heath",
  "BW": "Marsh Flats",
  "RU": "Scalding Tarn",
  "BG": "Verdant Catacombs",
  "RW": "Arid Mesa",
  "GU": "Misty Rainforest",
}

export const dual = {
  "UW": "Tundra",
  "BU": "Underground Sea",
  "BR": "Badlands",
  "GR": "Taiga",
  "GW": "Savannah",
  "BW": "Scrubland",
  "RU": "Volcanic Island",
  "BG": "Bayou",
  "RW": "Plateau",
  "GU": "Tropical Island",
}

export const shock = {
  "UW": "Hallowed Fountain",
  "BU": "Watery Grave",
  "BR": "Blood Crypt",
  "GR": "Stomping Ground",
  "GW": "Temple Garden",
  "BW": "Godless Shrine",
  "BG": "Overgrown Tomb",
  "GU": "Breeding Pool",
  "RU": "Steam Vents",
  "RW": "Sacred Foundry",
}
export const bond = {
  "UW": "Sea of Clouds",
  "BU": "Morphic Pool",
  "BR": "Luxury Suite",
  "GR": "Spire Garden",
  "GW": "Bountiful Promenade",
  "BW": "Vault of Champions",
  "RU": "Training Center",
  "BG": "Undergrowth Stadium",
  "RW": "Spectator Seating",
  "GU": "Rejuvenating Springs",
}
export const slow = {
  "UW": "Deserted Beach",
  "BU": "Shipwreck Marsh",
  "BR": "Haunted Ridge",
  "GR": "Rockfall Vale",
  "GW": "Overgrown Farmland",
  "BW": "Shattered Sanctum",
  "RU": "Stormcarved Coast",
  "BG": "Deathcap Glade",
  "RW": "Sundown Pass",
  "GU": "Dreamroot Cascade",
}
export const pain = {
  "UW": "Adarkar Wastes",
  "BU": "Underground River",
  "BR": "Sulfurous Springs",
  "GR": "Karplusan Forest",
  "GW": "Brushland",
  "BW": "Caves of Koilos",
  "RU": "Shivan Reef",
  "BG": "Llanowar Wastes",
  "RW": "Battlefield Forge",
  "GU": "Yavimaya Coast",
}
export const check = {
  "UW": "Glacial Fortress",
  "BU": "Drowned Catacomb",
  "BR": "Dragonskull Summit",
  "GR": "Rootbound Crag",
  "GW": "Sunpetal Grove",
  "BW": "Isolated Chapel",
  "RU": "Sulfur Falls",
  "BG": "Woodland Cemetery",
  "RW": "Clifftop Retreat",
  "GU": "Hinterland Harbor",
}
export const pathway = {
  "UW": "Hengegate Pathway",
  "BU": "Clearwater Pathway",
  "BR": "Blightstep Pathway",
  "GR": "Cragcrown Pathway",
  "GW": "Branchloft Pathway",
  "BW": "Brightclimb Pathway",
  "RU": "Riverglide Pathway",
  "BG": "Darkbore Pathway",
  "RW": "Needleverge Pathway",
  "GU": "Barkchannel Pathway",
}

export const filter = {
  "UW": "Mystic Gate",
  "BU": "Sunken Ruins",
  "BR": "Graven Cairns",
  "GR": "Fire-Lit Thicket",
  "GW": "Wooded Bastion",
  "BW": "Fetid Heath",
  "RU": "Cascade Bluffs",
  "BG": "Twilight Mire",
  "RW": "Rugged Prairie",
  "GU": "Flooded Grove",
}

export const horizon = {
  "BW": "Silent Clearing",
  "RU": "Fiery Islet",
  "BG": "Nurturing Peatland",
  "RW": "Sunbaked Canyon",
  "GU": "Waterlogged Grove",
}

export const tango = {
  "UW": "Prairie Stream",
  "BU": "Sunken Hollow",
  "BR": "Smoldering Marsh",
  "GR": "Cinder Glade",
  "GW": "Canopy Vista",
}

export const bounce = {
  "UW": "Azorius Chancery",
  "BU": "Dimir Aqueduct",
  "BR": "Rakdos Carnarium",
  "GR": "Gruul Turf",
  "GW": "Selesnya Sanctuary",
  "BW": "Orzhov Basilica",
  "RU": "Izzet Boilerworks",
  "BG": "Golgari Rot Farm",
  "RW": "Boros Garrison",
  "GU": "Simic Growth Chamber",
}

export const triome = {
  "GUW": "Seaside Citadel",
  "BUW": "Arcane Sanctum",
  "BRU": "Crumbling Necropolis",
  "BGR": "Savage Lands",
  "GRW": "Jungle Shrine",
  "BRW": "Nomad Outpost",
  "BGW": "Sandsteppe Citadel",
  "BGU": "Opulent Palace",
  "GRU": "Frontier Bivouac",
  "RUW": "Mystic Monastery",
}

export const triomeCycle = {
  "BRW": "Savai Triome",
  "BGW": "Indatha Triome",
  "BGU": "Zagoth Triome",
  "GRU": "Ketria Triome",
  "RUW": "Raugrin Triome",
  "GUW": "Spara's Headquarters",
  "BUW": "Raffine's Tower",
  "BRU": "Xander's Lounge",
  "BGR": "Ziatora's Proving Ground",
  "GRW": "Jetmir's Garden",
}

export const manaPips = {
  "Tundra": "UW",
  "Underground Sea": "BU",
  "Badlands": "BR",
  "Taiga": "GR",
  "Savannah": "GW",
  "Scrubland": "BW",
  "Volcanic Island": "RU",
  "Bayou": "BG",
  "Plateau": "RW",
  "Tropical Island": "GU",
  "Hallowed Fountain": "UW",
  "Watery Grave": "BU",
  "Blood Crypt": "BR",
  "Stomping Ground": "GR",
  "Temple Garden": "GW",
  "Godless Shrine": "BW",
  "Overgrown Tomb": "BG",
  "Breeding Pool": "GU",
  "Steam Vents": "RU",
  "Sacred Foundry": "RW",
  "Sea of Clouds": "UW",
  "Morphic Pool": "BU",
  "Luxury Suite": "BR",
  "Spire Garden": "GR",
  "Bountiful Promenade": "GW",
  "Vault of Champions": "BW",
  "Training Center": "RU",
  "Undergrowth Stadium": "BG",
  "Spectator Seating": "RW",
  "Rejuvenating Springs": "GU",
  "Deserted Beach": "UW",
  "Shipwreck Marsh": "BU",
  "Haunted Ridge": "BR",
  "Rockfall Vale": "GR",
  "Overgrown Farmland": "GW",
  "Shattered Sanctum": "BW",
  "Stormcarved Coast": "RU",
  "Deathcap Glade": "BG",
  "Sundown Pass": "RW",
  "Dreamroot Cascade": "GU",
  "Adarkar Wastes": "UW",
  "Underground River": "BU",
  "Sulfurous Springs": "BR",
  "Karplusan Forest": "GR",
  "Brushland": "GW",
  "Caves of Koilos": "BW",
  "Shivan Reef": "RU",
  "Llanowar Wastes": "BG",
  "Battlefield Forge": "RW",
  "Yavimaya Coast": "GU",
  "Glacial Fortress": "UW",
  "Drowned Catacomb": "BU",
  "Dragonskull Summit": "BR",
  "Rootbound Crag": "GR",
  "Sunpetal Grove": "GW",
  "Isolated Chapel": "BW",
  "Sulfur Falls": "RU",
  "Woodland Cemetery": "BG",
  "Clifftop Retreat": "RW",
  "Hinterland Harbor": "GU",
  "Hengegate Pathway": "UW",
  "Clearwater Pathway": "BU",
  "Blightstep Pathway": "BR",
  "Cragcrown Pathway": "GR",
  "Branchloft Pathway": "GW",
  "Brightclimb Pathway": "BW",
  "Riverglide Pathway": "RU",
  "Darkbore Pathway": "BG",
  "Needleverge Pathway": "RW",
  "Barkchannel Pathway": "GU",
  "Mystic Gate": "UW",
  "Sunken Ruins": "BU",
  "Graven Cairns": "BR",
  "Fire-Lit Thicket": "GR",
  "Wooded Bastion": "GW",
  "Fetid Heath": "BW",
  "Cascade Bluffs": "RU",
  "Twilight Mire": "BG",
  "Rugged Prairie": "RW",
  "Flooded Grove": "GU",
  "Silent Clearing": "BW",
  "Fiery Islet": "RU",
  "Nurturing Peatland": "BG",
  "Sunbaked Canyon": "RW",
  "Waterlogged Grove": "GU",
  "Prairie Stream": "UW",
  "Sunken Hollow": "BU",
  "Smoldering Marsh": "BR",
  "Cinder Glade": "GR",
  "Canopy Vista": "GW",
  "Azorius Chancery": "UW",
  "Dimir Aqueduct": "BU",
  "Rakdos Carnarium": "BR",
  "Gruul Turf": "GR",
  "Selesnya Sanctuary": "GW",
  "Orzhov Basilica": "BW",
  "Izzet Boilerworks": "RU",
  "Golgari Rot Farm": "BG",
  "Boros Garrison": "RW",
  "Simic Growth Chamber": "GU",
  "Seaside Citadel": "GUW",
  "Arcane Sanctum": "BUW",
  "Crumbling Necropolis": "BRU",
  "Savage Lands": "BGR",
  "Jungle Shrine": "GRW",
  "Nomad Outpost": "BRW",
  "Sandsteppe Citadel": "BGW",
  "Opulent Palace": "BGU",
  "Frontier Bivouac": "GRU",
  "Mystic Monastery": "RUW",
  "Savai Triome": "BRW",
  "Indatha Triome": "BGW",
  "Zagoth Triome": "BGU",
  "Ketria Triome": "GRU",
  "Raugrin Triome": "RUW",
  "Spara's Headquarters": "GUW",
  "Raffine's Tower": "BUW",
  "Xander's Lounge": "BRU",
  "Ziatora's Proving Ground": "BGR",
  "Jetmir's Garden": "GRW",
}